apiVersion: v1
kind: Service
metadata:
  name: hello-b
  namespace: ricxapp
spec:
  selector:
    app: hello-b
  ports:
    - name: rmr-data
      protocol: TCP
      port: 4560
      targetPort: 4560
